import type {
  DemoPerson,
  EquipmentItem,
  Transfer,
  Warehouse,
} from '../model/types'

const now = () => new Date().toISOString()

export const DEMO_PEOPLE: DemoPerson[] = [
  {
    id: 'u-admin',
    fullName: 'Админ Тестов',
    roleSlug: 'admin',
    warehouseIds: [],
  },
  {
    id: 'u-master-ivanov',
    fullName: 'Мастер Иванов',
    roleSlug: 'master',
    warehouseIds: [],
  },
  {
    id: 'u-master-sidorov',
    fullName: 'Мастер Сидоров',
    roleSlug: 'master',
    warehouseIds: [],
  },
  {
    id: 'u-keeper',
    fullName: 'Кладовщик Складской',
    roleSlug: 'keeper',
    warehouseIds: ['wh-north', 'wh-repair'],
  },
  {
    id: 'u-office',
    fullName: 'Офис Планирова',
    roleSlug: 'office',
    warehouseIds: [],
  },
]

export const DEMO_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-repair',
    name: 'Ремонт',
    slug: 'repair',
    isSystem: true,
    address: 'Системная база ремонта',
    keeperIds: ['u-keeper'],
  },
  {
    id: 'wh-north',
    name: 'База Север',
    slug: 'demo-north',
    isSystem: false,
    address: 'НПС «Северная», площадка А',
    keeperIds: ['u-keeper'],
  },
  {
    id: 'wh-south',
    name: 'База Юг',
    slug: 'demo-south',
    isSystem: false,
    address: 'НПС «Южная», площадка Б',
    keeperIds: [],
  },
]

export const DEMO_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'eq-1',
    name: 'Насос центробежный НЦ-80',
    factoryNumber: 'NC-80-4412',
    quantity: 1,
    type: 'SERIAL',
    condition: 'OK',
    hasDocuments: true,
    category: 'EQUIPMENT',
    ownerType: 'USER',
    ownerUserId: 'u-master-ivanov',
    fillStatus: 'OK',
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-03-12T10:00:00.000Z',
  },
  {
    id: 'eq-2',
    name: 'Сварочный инвертор',
    factoryNumber: 'SW-220-901',
    quantity: 1,
    type: 'SERIAL',
    condition: 'NEEDS_REPAIR',
    conditionNote: 'Плохой контакт массы',
    hasDocuments: false,
    category: 'EQUIPMENT',
    ownerType: 'USER',
    ownerUserId: 'u-master-ivanov',
    fillStatus: 'OK',
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-03-18T10:00:00.000Z',
  },
  {
    id: 'eq-3',
    name: 'Рукав напорный',
    factoryNumber: null,
    quantity: 24,
    type: 'CONSUMABLE',
    condition: 'OK',
    hasDocuments: false,
    category: 'EQUIPMENT',
    ownerType: 'WAREHOUSE',
    ownerWarehouseId: 'wh-north',
    fillStatus: 'OK',
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-03-05T10:00:00.000Z',
  },
  {
    id: 'eq-4',
    name: 'Шлифмашина угловая',
    factoryNumber: 'AG-125-77',
    quantity: 1,
    type: 'SERIAL',
    condition: 'IN_REPAIR',
    conditionNote: 'Замена подшипника',
    hasDocuments: true,
    category: 'EQUIPMENT',
    ownerType: 'WAREHOUSE',
    ownerWarehouseId: 'wh-repair',
    fillStatus: 'OK',
    createdAt: '2026-02-20T10:00:00.000Z',
    updatedAt: '2026-03-20T10:00:00.000Z',
  },
  {
    id: 'eq-5',
    name: 'Труба ПНД 110',
    factoryNumber: null,
    quantity: 40,
    type: 'CONSUMABLE',
    condition: 'OK',
    hasDocuments: false,
    category: 'EQUIPMENT',
    ownerType: 'WAREHOUSE',
    ownerWarehouseId: 'wh-south',
    fillStatus: 'OK',
    createdAt: '2026-01-08T10:00:00.000Z',
    updatedAt: '2026-02-28T10:00:00.000Z',
  },
  {
    id: 'eq-6',
    name: 'Генератор 5 кВт',
    factoryNumber: 'GEN-5K-112',
    quantity: 1,
    type: 'SERIAL',
    condition: 'OK',
    hasDocuments: true,
    category: 'EQUIPMENT',
    ownerType: 'USER',
    ownerUserId: 'u-master-sidorov',
    pendingTransferId: 'tr-pending-1',
    fillStatus: 'OK',
    createdAt: '2026-03-02T10:00:00.000Z',
    updatedAt: '2026-03-22T10:00:00.000Z',
  },
  {
    id: 'eq-7',
    name: 'Лестница алюминиевая 3 м',
    factoryNumber: 'LAD-3M-55',
    quantity: 1,
    type: 'SERIAL',
    condition: 'OK',
    hasDocuments: false,
    category: 'EQUIPMENT',
    ownerType: 'WAREHOUSE',
    ownerWarehouseId: 'wh-north',
    fillStatus: 'NEEDS_FIX',
    fillComment: 'Уточните заводской номер',
    createdAt: '2026-03-10T10:00:00.000Z',
    updatedAt: '2026-03-21T10:00:00.000Z',
  },
  {
    id: 'eq-8',
    name: 'Перчатки х/б',
    factoryNumber: null,
    quantity: 120,
    type: 'CONSUMABLE',
    condition: 'OK',
    hasDocuments: false,
    category: 'EQUIPMENT',
    ownerType: 'WAREHOUSE',
    ownerWarehouseId: 'wh-north',
    fillStatus: 'OK',
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
]

export const DEMO_TRANSFERS: Transfer[] = [
  {
    id: 'tr-pending-1',
    equipmentId: 'eq-6',
    equipmentName: 'Генератор 5 кВт',
    factoryNumber: 'GEN-5K-112',
    quantity: 1,
    status: 'PENDING',
    fromOwnerType: 'USER',
    fromUserId: 'u-master-sidorov',
    fromLabel: 'Мастер Сидоров',
    toOwnerType: 'USER',
    toUserId: 'u-master-ivanov',
    toLabel: 'Мастер Иванов',
    actorUserId: 'u-master-sidorov',
    createdAt: '2026-03-22T09:30:00.000Z',
  },
  {
    id: 'tr-done-1',
    equipmentId: 'eq-4',
    equipmentName: 'Шлифмашина угловая',
    factoryNumber: 'AG-125-77',
    quantity: 1,
    status: 'COMPLETED',
    fromOwnerType: 'USER',
    fromUserId: 'u-master-ivanov',
    fromLabel: 'Мастер Иванов',
    toOwnerType: 'WAREHOUSE',
    toWarehouseId: 'wh-repair',
    toLabel: 'Ремонт',
    actorUserId: 'u-master-ivanov',
    createdAt: '2026-03-20T11:00:00.000Z',
  },
  {
    id: 'tr-done-2',
    equipmentId: 'eq-3',
    equipmentName: 'Рукав напорный',
    factoryNumber: null,
    quantity: 10,
    status: 'COMPLETED',
    fromOwnerType: 'WAREHOUSE',
    fromWarehouseId: 'wh-south',
    fromLabel: 'База Юг',
    toOwnerType: 'WAREHOUSE',
    toWarehouseId: 'wh-north',
    toLabel: 'База Север',
    actorUserId: 'u-keeper',
    createdAt: '2026-03-05T14:20:00.000Z',
  },
]

export function cloneDemoState() {
  return {
    people: structuredClone(DEMO_PEOPLE),
    warehouses: structuredClone(DEMO_WAREHOUSES),
    equipment: structuredClone(DEMO_EQUIPMENT),
    transfers: structuredClone(DEMO_TRANSFERS),
    stamp: now(),
  }
}
