import { reportStoragePath, type DailyReport } from '../../shared.js'

export function reportsSeed(): DailyReport[] {
  return [
    {
      id: 'r-1',
      objectId: 'o-1',
      date: '2026-09-26',
      authorName: 'Иванов П.С.',
      workStartFrom: '08:00',
      workStartTo: '08:30',
      estimatedCompletion: '2026-05-15',
      dronePeriods: [{ from: '14:00', to: '15:30' }],
      staffItr: '2 / Петров, Сидоров',
      staffForemen: '1 / Козлов',
      staffWorkers: '8 / бригада «Север»',
      workStage: 'Дефектоскопия днища, подготовка к АКЗ.',
      techMeans: 'Насос НЦ-80 зав.№4412; компрессор К-3 зав.№118.',
      volumes: 'Откачано 120 м³; зачищено 85 м².',
      workItems: [{ itemId: 'w-2', name: 'Дефектоскопия днища', unit: 'м²', volume: 85 }],
      ppe: 'Костюмы химзащитные — 8 шт., перчатки — 16 пар.',
      nextDay: 'Продолжение дефектоскопии, разметка зон АКЗ.',
      problems: '',
      createdAt: '2026-09-26T17:10:00.000Z',
      updatedAt: '2026-09-26T17:10:00.000Z',
      storagePath: reportStoragePath('o-1', '2026-09-26'),
    },
    {
      id: 'r-2',
      objectId: 'o-1',
      date: '2026-09-27',
      authorName: 'Иванов П.С.',
      workStartFrom: '07:45',
      workStartTo: '08:15',
      estimatedCompletion: '2026-05-15',
      dronePeriods: [],
      staffItr: '2 / Петров, Сидоров',
      staffForemen: '1 / Козлов',
      staffWorkers: '8 / бригада «Север»',
      workStage: 'Дефектоскопия днища — завершение секторов А–В.',
      techMeans: 'Насос НЦ-80 зав.№4412; УЗК-комплект.',
      volumes: 'Проконтролировано 140 м².',
      workItems: [{ itemId: 'w-2', name: 'Дефектоскопия днища', unit: 'м²', volume: 140 }],
      ppe: 'Перчатки — 8 пар.',
      nextDay: 'Начало антикоррозионного покрытия (грунт).',
      problems: 'Задержка поставки грунта заказчиком (~1 сутки).',
      createdAt: '2026-09-27T16:40:00.000Z',
      updatedAt: '2026-09-27T16:40:00.000Z',
      storagePath: reportStoragePath('o-1', '2026-09-27'),
    },
    {
      id: 'r-3',
      objectId: 'o-3',
      date: '2026-04-20',
      authorName: 'Смирнова А.В.',
      workStartFrom: '08:00',
      workStartTo: '08:20',
      estimatedCompletion: '2026-04-30',
      dronePeriods: [],
      staffItr: '1',
      staffForemen: '1',
      staffWorkers: '6',
      workStage: 'Комплексная зачистка — финальный проход.',
      techMeans: 'Мойка высокого давления зав.№22.',
      volumes: 'Зачищено 100%.',
      workItems: [{ itemId: 'w-6', name: 'Комплексная зачистка', unit: '%', volume: 100 }],
      ppe: '',
      nextDay: 'Сдача объекта заказчику.',
      problems: '',
      createdAt: '2026-04-20T15:00:00.000Z',
      updatedAt: '2026-04-20T15:00:00.000Z',
      storagePath: reportStoragePath('o-3', '2026-04-20'),
    },
  ]
}
