import type {
  DemoPerson,
  EquipmentDocument,
  EquipmentHistoryEntry,
  EquipmentItem,
  Transfer,
  Warehouse,
} from '../../shared.js'

export type SeedPerson = Omit<DemoPerson, 'warehouseIds'>

export interface EquipmentSeed {
  people: SeedPerson[]
  warehouses: Warehouse[]
  items: EquipmentItem[]
  transfers: Transfer[]
  history: EquipmentHistoryEntry[]
}

function item(
  partial: Omit<EquipmentItem, 'documents' | 'category' | 'hasDocuments' | 'fillStatus'> & Partial<EquipmentItem>,
): EquipmentItem {
  const documents = partial.documents ?? []
  return {
    category: 'EQUIPMENT',
    fillStatus: 'OK',
    ...partial,
    documents,
    hasDocuments: documents.length > 0,
  }
}

function doc(id: string, itemId: string, fileName: string, addedAt: string, addedBy: string): EquipmentDocument {
  return {
    id,
    fileName,
    mimeType: 'application/pdf',
    size: 0,
    storagePath: `mock-disk/Оборудование/${itemId}/${fileName}`,
    addedAt,
    addedBy,
  }
}

export function equipmentSeed(): EquipmentSeed {
  return {
    people: [
      { id: 'u-admin', fullName: 'Админ Тестов', roleSlug: 'admin' },
      { id: 'u-master-ivanov', fullName: 'Мастер Иванов', roleSlug: 'master' },
      { id: 'u-master-sidorov', fullName: 'Мастер Сидоров', roleSlug: 'master' },
      { id: 'u-keeper', fullName: 'Кладовщик Складской', roleSlug: 'keeper' },
      { id: 'u-office', fullName: 'Офис Планирова', roleSlug: 'office' },
    ],
    warehouses: [
      {
        id: 'wh-repair',
        name: 'Ремонт',
        slug: 'repair',
        isSystem: true,
        address: 'Системная база ремонта',
        keeperIds: ['u-keeper'],
      },
      {
        id: 'wh-north',
        name: 'База Север',
        slug: 'demo-north',
        isSystem: false,
        address: 'НПС «Северная», площадка А',
        keeperIds: ['u-keeper'],
      },
      {
        id: 'wh-south',
        name: 'База Юг',
        slug: 'demo-south',
        isSystem: false,
        address: 'НПС «Южная», площадка Б',
        keeperIds: [],
      },
    ],
    items: [
      item({
        id: 'eq-1',
        name: 'Насос центробежный НЦ-80',
        factoryNumber: 'NC-80-4412',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        documents: [doc('doc-1', 'eq-1', 'Паспорт НЦ-80.pdf', '2026-03-01T10:00:00.000Z', 'Админ Тестов')],
        ownerType: 'USER',
        ownerUserId: 'u-master-ivanov',
        createdAt: '2026-03-01T10:00:00.000Z',
        updatedAt: '2026-03-12T10:00:00.000Z',
      }),
      item({
        id: 'eq-2',
        name: 'Сварочный инвертор',
        factoryNumber: 'SW-220-901',
        quantity: 1,
        type: 'SERIAL',
        condition: 'NEEDS_REPAIR',
        conditionNote: 'Плохой контакт массы',
        ownerType: 'USER',
        ownerUserId: 'u-master-ivanov',
        createdAt: '2026-02-10T10:00:00.000Z',
        updatedAt: '2026-03-18T10:00:00.000Z',
      }),
      item({
        id: 'eq-3',
        name: 'Рукав напорный',
        factoryNumber: null,
        quantity: 24,
        type: 'CONSUMABLE',
        condition: 'OK',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-north',
        createdAt: '2026-01-15T10:00:00.000Z',
        updatedAt: '2026-03-05T10:00:00.000Z',
      }),
      item({
        id: 'eq-4',
        name: 'Шлифмашина угловая',
        factoryNumber: 'AG-125-77',
        quantity: 1,
        type: 'SERIAL',
        condition: 'IN_REPAIR',
        conditionNote: 'Замена подшипника',
        documents: [doc('doc-2', 'eq-4', 'Акт дефектовки.pdf', '2026-03-20T11:05:00.000Z', 'Кладовщик Складской')],
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-repair',
        createdAt: '2026-02-20T10:00:00.000Z',
        updatedAt: '2026-03-20T10:00:00.000Z',
      }),
      item({
        id: 'eq-5',
        name: 'Труба ПНД 110',
        factoryNumber: null,
        quantity: 40,
        type: 'CONSUMABLE',
        condition: 'OK',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-south',
        createdAt: '2026-01-08T10:00:00.000Z',
        updatedAt: '2026-02-28T10:00:00.000Z',
      }),
      item({
        id: 'eq-6',
        name: 'Генератор 5 кВт',
        factoryNumber: 'GEN-5K-112',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        ownerType: 'USER',
        ownerUserId: 'u-master-sidorov',
        pendingTransferId: 'tr-pending-1',
        createdAt: '2026-03-02T10:00:00.000Z',
        updatedAt: '2026-03-22T10:00:00.000Z',
      }),
      item({
        id: 'eq-7',
        name: 'Лестница алюминиевая 3 м',
        factoryNumber: 'LAD-3M-55',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-north',
        fillStatus: 'NEEDS_FIX',
        fillComment: 'Уточните заводской номер',
        createdAt: '2026-03-10T10:00:00.000Z',
        updatedAt: '2026-03-21T10:00:00.000Z',
      }),
      item({
        id: 'eq-8',
        name: 'Перчатки х/б',
        factoryNumber: null,
        quantity: 120,
        type: 'CONSUMABLE',
        condition: 'OK',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-north',
        createdAt: '2026-03-01T10:00:00.000Z',
        updatedAt: '2026-03-01T10:00:00.000Z',
      }),
      item({
        id: 'veh-1',
        category: 'VEHICLE',
        name: 'ГАЗель NEXT',
        factoryNumber: 'A123BC77',
        plateNumber: 'A123BC77',
        vehicleKind: 'TRUCK',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        documents: [doc('doc-3', 'veh-1', 'СТС ГАЗель.pdf', '2026-02-01T09:00:00.000Z', 'Админ Тестов')],
        ownerType: 'USER',
        ownerUserId: 'u-master-ivanov',
        createdAt: '2026-02-01T09:00:00.000Z',
        updatedAt: '2026-02-01T09:00:00.000Z',
      }),
      item({
        id: 'veh-2',
        category: 'VEHICLE',
        name: 'Экскаватор-погрузчик JCB 3CX',
        factoryNumber: 'E777KX116',
        plateNumber: 'E777KX116',
        vehicleKind: 'SPECIAL',
        quantity: 1,
        type: 'SERIAL',
        condition: 'NEEDS_REPAIR',
        conditionNote: 'Течь гидравлики',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-north',
        createdAt: '2026-01-20T09:00:00.000Z',
        updatedAt: '2026-03-15T09:00:00.000Z',
      }),
      item({
        id: 'veh-3',
        category: 'VEHICLE',
        name: 'Прицеп бортовой',
        factoryNumber: 'AA123477',
        plateNumber: 'AA123477',
        vehicleKind: 'TRAILER',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-south',
        createdAt: '2026-01-22T09:00:00.000Z',
        updatedAt: '2026-01-22T09:00:00.000Z',
      }),
      item({
        id: 'card-1',
        category: 'CARD',
        name: 'Топливная карта 7005 1234 5678',
        factoryNumber: '7005 1234 5678',
        cardNumber: '7005 1234 5678',
        cardKind: 'FUEL',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        ownerType: 'USER',
        ownerUserId: 'u-master-ivanov',
        createdAt: '2026-02-05T09:00:00.000Z',
        updatedAt: '2026-02-05T09:00:00.000Z',
      }),
      item({
        id: 'card-2',
        category: 'CARD',
        name: 'Транспондер ГАЗель',
        factoryNumber: 'T-310045',
        cardNumber: 'T-310045',
        cardKind: 'TRANSPONDER',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        ownerType: 'USER',
        ownerUserId: 'u-master-sidorov',
        createdAt: '2026-02-06T09:00:00.000Z',
        updatedAt: '2026-02-06T09:00:00.000Z',
      }),
      item({
        id: 'card-3',
        category: 'CARD',
        name: 'Бизнес-карта ****4821',
        factoryNumber: '4821',
        cardNumber: '4821',
        cardKind: 'BUSINESS',
        quantity: 1,
        type: 'SERIAL',
        condition: 'OK',
        ownerType: 'WAREHOUSE',
        ownerWarehouseId: 'wh-north',
        createdAt: '2026-02-07T09:00:00.000Z',
        updatedAt: '2026-02-07T09:00:00.000Z',
      }),
    ],
    transfers: [
      {
        id: 'tr-pending-1',
        equipmentId: 'eq-6',
        equipmentName: 'Генератор 5 кВт',
        factoryNumber: 'GEN-5K-112',
        quantity: 1,
        status: 'PENDING',
        fromOwnerType: 'USER',
        fromUserId: 'u-master-sidorov',
        fromLabel: 'Мастер Сидоров',
        toOwnerType: 'USER',
        toUserId: 'u-master-ivanov',
        toLabel: 'Мастер Иванов',
        actorUserId: 'u-master-sidorov',
        actorName: 'Мастер Сидоров',
        createdAt: '2026-03-22T09:30:00.000Z',
      },
      {
        id: 'tr-done-1',
        equipmentId: 'eq-4',
        equipmentName: 'Шлифмашина угловая',
        factoryNumber: 'AG-125-77',
        quantity: 1,
        status: 'COMPLETED',
        fromOwnerType: 'USER',
        fromUserId: 'u-master-ivanov',
        fromLabel: 'Мастер Иванов',
        toOwnerType: 'WAREHOUSE',
        toWarehouseId: 'wh-repair',
        toLabel: 'Ремонт',
        actorUserId: 'u-master-ivanov',
        actorName: 'Мастер Иванов',
        createdAt: '2026-03-20T11:00:00.000Z',
      },
      {
        id: 'tr-done-2',
        equipmentId: 'eq-3',
        equipmentName: 'Рукав напорный',
        factoryNumber: null,
        quantity: 10,
        status: 'COMPLETED',
        fromOwnerType: 'WAREHOUSE',
        fromWarehouseId: 'wh-south',
        fromLabel: 'База Юг',
        toOwnerType: 'WAREHOUSE',
        toWarehouseId: 'wh-north',
        toLabel: 'База Север',
        actorUserId: 'u-keeper',
        actorName: 'Кладовщик Складской',
        createdAt: '2026-03-05T14:20:00.000Z',
      },
    ],
    history: [
      {
        id: 'h-1',
        equipmentId: 'eq-4',
        action: 'CONDITION_CHANGED',
        actorUserId: 'u-master-ivanov',
        actorName: 'Мастер Иванов',
        details: 'Исправное → В ремонте. Замена подшипника',
        createdAt: '2026-03-20T10:58:00.000Z',
      },
      {
        id: 'h-2',
        equipmentId: 'eq-4',
        action: 'MOVED_TO_REPAIR',
        actorUserId: 'u-master-ivanov',
        actorName: 'Мастер Иванов',
        details: 'Мастер Иванов → Ремонт',
        createdAt: '2026-03-20T11:00:00.000Z',
      },
      {
        id: 'h-3',
        equipmentId: 'eq-3',
        action: 'TRANSFER_COMPLETED',
        actorUserId: 'u-keeper',
        actorName: 'Кладовщик Складской',
        details: 'База Юг → База Север, 10 шт.',
        createdAt: '2026-03-05T14:20:00.000Z',
      },
      {
        id: 'h-4',
        equipmentId: 'eq-6',
        action: 'TRANSFER_CREATED',
        actorUserId: 'u-master-sidorov',
        actorName: 'Мастер Сидоров',
        details: 'Мастер Сидоров → Мастер Иванов',
        createdAt: '2026-03-22T09:30:00.000Z',
      },
    ],
  }
}
